services:
  pokemonback.botbattleapi:
    image: ${DOCKER_REGISTRY-}pokemonbackbotbattleapi
    build:
      context: .
      dockerfile: PokemonBack.BotBattleAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=yourpassword;Database=BattleLogDb
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: BattleLogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  pgdata:
