---
apiVersion: v1
kind: Service
metadata:
  name: pokemonback-botbattleapi
spec:
  type: ClusterIP
  selector:
    app: pokemonback-botbattleapi
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
